export { default as About } from './About';
export { default as WIP } from './WIP';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Forgot } from './Forgot';
export { default as ChangePassword } from './ChangePassword';
export { default as ProtectedRoute } from './ProtectedRoute';
export { default as Home } from './Home';
export { default as UserVerified } from './UserVerified';
